import { Product } from './types';

export const FULL_ACCESS_PRODUCT: Product = {
  id: 'BUNDLE_ALL',
  code: 'ALL-ACCESS',
  name: 'DaBao',
  description: 'The ultimate pack. Takeaway everything. Immediate access to all 25+ notes and future uploads.',
  price: 89.0,
  category: 'Note',
  tags: ['bundle', 'all', 'premium'],
  image: 'https://placehold.co/600x400/000000/FFFFFF?text=DaBao',
  filterCategory: 'All',
  googleDriveId: 'BUNDLE-ROOT-FOLDER'
};

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    code: 'CS101',
    name: 'Introduction to Computer Science',
    description: 'Includes midterm and final review highlights, Java syntax summary, and past exam analysis.',
    price: 10.0,
    category: 'Note',
    tags: ['java', 'programming', 'basics'],
    image: 'https://placehold.co/600x400/4F46E5/FFFFFF?text=CS101+Preview',
    filterCategory: 'Year 1',
    googleDriveId: '1A-CS101-MockDriveId-XyZ'
  },
  {
    id: '2',
    code: 'MATH203',
    name: 'Linear Algebra',
    description: 'Handwritten notes on matrix operations, eigenvalues, vector spaces, with Matlab code examples.',
    price: 10.0,
    category: 'Note',
    tags: ['math', 'matrices', 'engineering'],
    image: 'https://placehold.co/600x400/10B981/FFFFFF?text=MATH203+Notes',
    filterCategory: 'Year 2',
    googleDriveId: '1B-MATH203-MockDriveId-AbC'
  },
  {
    id: '3',
    code: 'ECON100',
    name: 'Microeconomics',
    description: 'Supply and demand diagrams, market structure analysis, perfect for business students.',
    price: 10.0,
    category: 'Note',
    tags: ['business', 'economics', 'graphs'],
    image: 'https://placehold.co/600x400/F59E0B/FFFFFF?text=ECON100+Graphs',
    filterCategory: 'Prescribed Elective',
    googleDriveId: '1C-ECON100-MockDriveId-123'
  },
  {
    id: '4',
    code: 'TOOL_OCR',
    name: 'PDF Auto-OCR Tool (Python Script)',
    description: 'A script to automatically convert scanned PDFs to searchable text, supporting multi-language.',
    price: 10.0,
    category: 'Tool',
    tags: ['python', 'automation', 'productivity'],
    image: 'https://placehold.co/600x400/374151/FFFFFF?text=OCR+Tool+UI',
    filterCategory: 'Technical Elective',
    googleDriveId: '1D-TOOL-OCR-MockDriveId-456'
  },
  {
    id: '5',
    code: 'PSYCH101',
    name: 'Introduction to Psychology',
    description: 'From Freud to modern cognitive psychology, with flashcards for exam points.',
    price: 10.0,
    category: 'Note',
    tags: ['humanities', 'social science'],
    image: 'https://placehold.co/600x400/EC4899/FFFFFF?text=Psych+MindMap',
    filterCategory: 'Prescribed Elective',
    googleDriveId: '1E-PSYCH101-MockDriveId-789'
  },
  {
    id: '6',
    code: 'FIN301',
    name: 'Corporate Finance',
    description: 'Includes CAPM model, WACC calculation, DCF model Excel templates and notes.',
    price: 10.0,
    category: 'Note',
    tags: ['finance', 'business', 'excel'],
    image: 'https://placehold.co/600x400/6366F1/FFFFFF?text=Finance+Models',
    filterCategory: 'Year 3',
    googleDriveId: '1F-FIN301-MockDriveId-987'
  },
  {
    id: '7',
    code: 'ARCH202',
    name: 'History of Modern Architecture',
    description: 'Detailed analysis of Bauhaus style, architectural sketches, reference for final essays.',
    price: 10.0,
    category: 'Note',
    tags: ['architecture', 'history', 'design'],
    image: 'https://placehold.co/600x400/8B5CF6/FFFFFF?text=Arch+Sketches',
    filterCategory: 'Design Elective',
    googleDriveId: '1G-ARCH202-MockDriveId-654'
  },
  {
    id: '8',
    code: 'STAT201',
    name: 'Statistics Basics',
    description: 'Hypothesis testing, regression analysis steps, SPSS guide.',
    price: 10.0,
    category: 'Note',
    tags: ['math', 'data', 'spss'],
    image: 'https://placehold.co/600x400/EF4444/FFFFFF?text=Data+Analysis',
    filterCategory: 'Year 2',
    googleDriveId: '1H-STAT201-MockDriveId-321'
  },
  {
    id: '9',
    code: 'MECH400',
    name: 'Advanced Mechanical Design',
    description: 'Final year project reference, CAD source files, FEA reports.',
    price: 10.0,
    category: 'Note',
    tags: ['engineering', 'cad', 'final year'],
    image: 'https://placehold.co/600x400/059669/FFFFFF?text=CAD+Drawings',
    filterCategory: 'Year 4',
    googleDriveId: '1I-MECH400-MockDriveId-000'
  },
  {
    id: '10',
    code: 'CS102',
    name: 'Data Structures',
    description: 'Linked lists, trees, graphs, and hash tables implementation guide.',
    price: 10.0,
    category: 'Note',
    tags: ['cs', 'programming'],
    image: 'https://placehold.co/600x400/3B82F6/FFFFFF?text=Data+Structures',
    filterCategory: 'Year 1',
    googleDriveId: '1J-CS102-Mock'
  },
  {
    id: '11',
    code: 'PHYS101',
    name: 'Physics I: Mechanics',
    description: 'Newtonian mechanics, work, energy, and power. Solved problem sets.',
    price: 10.0,
    category: 'Note',
    tags: ['science', 'physics'],
    image: 'https://placehold.co/600x400/F97316/FFFFFF?text=Physics+I',
    filterCategory: 'Year 1',
    googleDriveId: '1K-PHYS101-Mock'
  },
  {
    id: '12',
    code: 'CHEM101',
    name: 'General Chemistry',
    description: 'Periodic table trends, stoichiometry, and bonding theories summarized.',
    price: 10.0,
    category: 'Note',
    tags: ['science', 'chemistry'],
    image: 'https://placehold.co/600x400/14B8A6/FFFFFF?text=Chemistry',
    filterCategory: 'Year 1',
    googleDriveId: '1L-CHEM101-Mock'
  },
  {
    id: '13',
    code: 'CS201',
    name: 'Algorithms',
    description: 'Sorting, searching, dynamic programming, and complexity analysis.',
    price: 10.0,
    category: 'Note',
    tags: ['cs', 'algorithms'],
    image: 'https://placehold.co/600x400/8B5CF6/FFFFFF?text=Algorithms',
    filterCategory: 'Year 2',
    googleDriveId: '1M-CS201-Mock'
  },
  {
    id: '14',
    code: 'MATH201',
    name: 'Calculus II',
    description: 'Integration techniques, sequences, series, and polar coordinates.',
    price: 10.0,
    category: 'Note',
    tags: ['math', 'calculus'],
    image: 'https://placehold.co/600x400/EC4899/FFFFFF?text=Calculus+II',
    filterCategory: 'Year 2',
    googleDriveId: '1N-MATH201-Mock'
  },
  {
    id: '15',
    code: 'ENG201',
    name: 'Technical Writing',
    description: 'Guide to writing reports, proposals, and manuals for engineers.',
    price: 10.0,
    category: 'Note',
    tags: ['writing', 'skills'],
    image: 'https://placehold.co/600x400/64748B/FFFFFF?text=Tech+Writing',
    filterCategory: 'Prescribed Elective',
    googleDriveId: '1O-ENG201-Mock'
  },
  {
    id: '16',
    code: 'ART101',
    name: 'Art History',
    description: 'Renaissance to Contemporary art movements overview.',
    price: 10.0,
    category: 'Note',
    tags: ['art', 'history'],
    image: 'https://placehold.co/600x400/A855F7/FFFFFF?text=Art+History',
    filterCategory: 'Prescribed Elective',
    googleDriveId: '1P-ART101-Mock'
  },
  {
    id: '17',
    code: 'CS301',
    name: 'Operating Systems',
    description: 'Processes, threads, scheduling, deadlocks, and memory management.',
    price: 10.0,
    category: 'Note',
    tags: ['cs', 'os'],
    image: 'https://placehold.co/600x400/334155/FFFFFF?text=OS',
    filterCategory: 'Year 3',
    googleDriveId: '1Q-CS301-Mock'
  },
  {
    id: '18',
    code: 'CS302',
    name: 'Database Systems',
    description: 'SQL mastery, normalization, indexing, and transaction management.',
    price: 10.0,
    category: 'Note',
    tags: ['cs', 'database'],
    image: 'https://placehold.co/600x400/0EA5E9/FFFFFF?text=Databases',
    filterCategory: 'Year 3',
    googleDriveId: '1R-CS302-Mock'
  },
  {
    id: '19',
    code: 'BIO101',
    name: 'Biology Basics',
    description: 'Cell structure, genetics, evolution, and ecology fundamentals.',
    price: 10.0,
    category: 'Note',
    tags: ['science', 'biology'],
    image: 'https://placehold.co/600x400/22C55E/FFFFFF?text=Biology',
    filterCategory: 'Year 1',
    googleDriveId: '1S-BIO101-Mock'
  },
  {
    id: '20',
    code: 'MKT201',
    name: 'Marketing Principles',
    description: '4Ps, consumer behavior, and market research techniques.',
    price: 10.0,
    category: 'Note',
    tags: ['business', 'marketing'],
    image: 'https://placehold.co/600x400/F43F5E/FFFFFF?text=Marketing',
    filterCategory: 'Year 2',
    googleDriveId: '1T-MKT201-Mock'
  },
  {
    id: '21',
    code: 'CS401',
    name: 'Artificial Intelligence',
    description: 'Search algorithms, machine learning basics, and neural networks.',
    price: 10.0,
    category: 'Note',
    tags: ['cs', 'ai'],
    image: 'https://placehold.co/600x400/6366F1/FFFFFF?text=AI+Basics',
    filterCategory: 'Technical Elective',
    googleDriveId: '1U-CS401-Mock'
  },
  {
    id: '22',
    code: 'CS402',
    name: 'Computer Networks',
    description: 'OSI model, TCP/IP, routing protocols, and network security.',
    price: 10.0,
    category: 'Note',
    tags: ['cs', 'networks'],
    image: 'https://placehold.co/600x400/0F172A/FFFFFF?text=Networks',
    filterCategory: 'Technical Elective',
    googleDriveId: '1V-CS402-Mock'
  },
  {
    id: '23',
    code: 'DES101',
    name: 'Design Fundamentals',
    description: 'Color theory, typography, composition, and layout design.',
    price: 10.0,
    category: 'Note',
    tags: ['design', 'art'],
    image: 'https://placehold.co/600x400/DB2777/FFFFFF?text=Design',
    filterCategory: 'Design Elective',
    googleDriveId: '1W-DES101-Mock'
  },
  {
    id: '24',
    code: 'DES201',
    name: 'UX/UI Design',
    description: 'User research, wireframing, prototyping, and usability testing.',
    price: 10.0,
    category: 'Note',
    tags: ['design', 'ux'],
    image: 'https://placehold.co/600x400/7C3AED/FFFFFF?text=UX+UI',
    filterCategory: 'Design Elective',
    googleDriveId: '1X-DES201-Mock'
  },
  {
    id: '25',
    code: 'MECH401',
    name: 'Robotics',
    description: 'Kinematics, dynamics, control systems, and robot programming.',
    price: 10.0,
    category: 'Note',
    tags: ['engineering', 'robotics'],
    image: 'https://placehold.co/600x400/BE123C/FFFFFF?text=Robotics',
    filterCategory: 'Year 4',
    googleDriveId: '1Y-MECH401-Mock'
  }
];